# Generated by Django 3.1.5 on 2021-01-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20210125_0736'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='signup_profile',
        ),
    ]
