# Generated by Django 3.1.5 on 2021-01-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='', width_field=200),
        ),
    ]
